import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./components/navbar";
import ProductMarquee from "./components/marquee";
import Footer from "./components/Footer";
import AuthToast from "./components/AuthToast";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <Toaster position="top-center" reverseOrder={false} />

        <AuthToast />

        <Navbar />
        <ProductMarquee />
        {children}
        <Footer />
      </body>
    </html>
  );
}